baseURL = "https://1hiking.github.io"
languageCode = "en-us"
relativeURLs = true
title = "Nice Polar Blog"
theme = "SimpleTheme"

[build]
writeStats = true

[menu]

[[menu.main]]
homepage = "Posts"
name = "Posts"
url = "/posts/"
weight = 10

[params]
dateFormat = "02 of January of 2006"
copyright = "1hiking" # Will be displayed on Footer
logo = "/img/PolarBear.svg" # Supports SVG.
logoalt = "A white polar bear" # alt description of the logo.
  [params.author]
    name = "1hiking"
    github = "1hiking" # https://github.com/XXXX


[permalinks]
posts = ':section/:year/:month/:title/'

[markup]
  [markup.highlight]
    style = 'nord'
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
