baseURL = "https://1hiking.github.io"
languageCode = "en-us"
relativeURLs = true
title = "Nice Polar Blog"
theme = "SimpleTheme"
# Enables automatic nav
sectionPagesMenu = "main"

[params]
dateFormat = "02 of January of 2006"
copyright = "1hiking" # Will be displayed on Footer
footerText = "\"Nice page bro\"" # Any text you might want to display will go here.
logo = "/img/PolarBear.svg" # Supports SVG.
logoalt = "A white polar bear" # alt description of the logo.
postCSS = true # For postCSS support.

[author]
name = "1hiking"
github = "1hiking" # https://github.com/XXXX

[permalinks]
posts = ':section/:year/:month/:title/'

[markup]
  [markup.highlight]
    style = 'nord'
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
